### ISSUE TITLE
Ionic Typescript tracking custom events. AppCenter is not defined 

### ISSUE THREAD

**Issue by ShankarSumanth** [Microsoft/appcenter-sdk-cordova#20]
How does one set this up with Ionic and Typescript and track custom events? 

Note: I have the config.xml set and can see basic analytics.  My issue is  with custom trackEvents.

`AppCenter.Analytics.trackEvent('Home Page Loaded');` does not work because AppCenter it is not defined. 

All of these are tested on a basic/blank Ionic APP.

Solutions 1: 

`import * as  AppCenter from 'cordova-plugin-appcenter-analytics/www/Analytics.js';`
problem : build time error `cordova/exec` cannot be found

Solution 2: 
`import * as  AppCenter from 'cordova-plugin-appcenter-analytics'`
problem: cannot find module 'cordova-plugin-appcenter-analytics'.

Solution 3: 
`declare var AppCenter`
problem: AppCenter is not defined. 

How should this be integrated in a `.ts` file to get it working?

Additional Info: 
Just create a basic Ionic APP with CLI. 
Add the required cordova appcenter plugin's
Configure the config.xml with app_secret and enable analytics in js 
Go to Homepage and try to send custom Analytics event

**Comment by microwales** [comment]
Currently working for me in IOS and Android for default analytics data no extra code. Just added the plugin and configure config.xml as specified.

If you are running from IONIC:
Ensure the plugins are added to your project:
Then:
    var _windows: any = window;// { OrderNumber: orderNumber, User: userName }
    _windows.AppCenter.Analytics.trackEvent(......);
Working for me in Android/. Currently having issue in iOS (will update this if resolved in iOS)

Thanks.

**Comment by ShankarSumanth** [comment]
@microwales 

what plugins should be added to the project. Can you please provide me with a code sample? Here is my current setup 

```
corvoda version: 8.0.0
```

config.xml
```
<platform name="ios">
    <preference name="APP_SECRET" value="mySecretValueFromCodePushDashboard" />
</platform>
<engine name="ios" spec="4.5.4" />
<engine name="android" spec="7.0.0" />

```

homepage.ts from the ionic blank starter 
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  private webWiew: any = window;

  constructor(public navCtrl: NavController) {
    console.log('Home page loaded');
    this.webWiew.AppCenter.Analytics.trackEvent('Home Page loaded');
  }
}

```

AppModule.ts
```
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { CodePush } from '@ionic-native/code-push';

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    CodePush,
    { provide: ErrorHandler, useClass: IonicErrorHandler }
  ]
})
export class AppModule { }
```

What am i missing?

**Comment by microwales** [comment]
@ShankarSumanth 
Yes it appears you already added the plugins based on your config.xml  posted.
Just to be sure everything is fine remove and re-add the plugins.
If you want to run this for android generate and add the secret key for Android.
Run and app and check the appcenter to see if there are Analytics Data or Crash (hope not :) ) Data
To track custom events, use this line of code to access the plugin and track event:

var _windows: any = window;
 _windows.AppCenter.Analytics.trackEvent(......);

Works for me in Android/iOS Cordova version 6.3.1 (surprisingly)

Cheers

**Comment by pniko** [comment]
@ShankarSumanth Are you still experiencing any issues with this? @sergey-akhalkov let's follow up and have someone take a look if there is still a problem.

**Comment by ShankarSumanth** [comment]
Hi @sergey-akhalkov , yes this issue still exists. I can setup a git repo and maybe you can take a look at what is wrong with the configuration? But like I said, the documentation for cordova is does not say how the Appcenter should be accessed. I did try it with window.AppCenter but still does not work. 

Let me know if a git repo would help.

**Comment by sergey-akhalkov** [comment]
Hi @ShankarSumanth, thanks for reaching me out and sorry for the delayed response. 

>I can setup a git repo and maybe you can take a look at what is wrong with the configuration?

The demo repo that we can analyze to understand what goes wrong would be perfect, so could you please share it with us?

>But like I said, the documentation for cordova is does not say how the Appcenter should be accessed

Got it, let's investigate what the issue is with modules importing, then we'll fix the module's exports if needed and update docs to improve modules installation/configuration process. 

Thank you for your help and sharing the concerns, the feedback is really important for us and it allows to make the SDK better.

Please let me know if you have any questions.

**Comment by sergey-akhalkov** [comment]
Hi @ShankarSumanth, just a friendly ping, do you have any updates?

**Comment by ShankarSumanth** [comment]
Hey Sergey, 

Sorry i couldn’t do it earlier. Had a busy week. I will push the project EOD today and update on this ticket

**Comment by ShankarSumanth** [comment]
Hi @sergey-akhalkov , 

Looks like the issue has resolved itself. Strange!! It's working now the way suggested by @microwales . I cannot reproduce this issue anymore. 

Thanks for all the help and support. I would suggest an edit to the documentation though on how to use the Analytics events with IONIC/Typescript. It's exactly like microwales mentioned. 

I will close this issue now

Thanks again :)

**Comment by ShankarSumanth** [comment]
In case, if others stumble upon this issue and need a full working code. You can refer it here. ust remember to add your `SECRET_KEY`
https://github.com/ShankarSumanth/ionic-analytics-test/blob/master/src/pages/home/home.ts

**Comment by sergey-akhalkov** [comment]
Hi @ShankarSumanth, got it, thanks for the update!

**Comment by rroa** [comment]
Hi, I believe this issue has not been closed. @sergey-akhalkov @ShankarSumanth 

I'm facing the same issues, even when downloading the repo referenced above. The `AppCenter` object is undefined.

**Comment by max-mironov** [comment]
Hey @rroa, sorry for delay from our side, could you please take a look at my response [here](https://github.com/Microsoft/appcenter-sdk-cordova/issues/26#issuecomment-377481113) and let us know if it helps.
